### ISSUE TITLE
OS9 Boot screen barf

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beretta42/legsforth#2]
```
Using the OS9 boot method will cause "screen barf", but not otherwise harm 
booting.  I'm leaving this alone for a while... it works better than clearing 
the screen...


```

Original issue reported on code.google.com by `berett...@gmail.com` on 7 Nov 2014 at 9:35

**Comment by beretta42** [comment]
Latest commit fixes this by requiring the NITROS9 kernel to do more of it's own work.  It clears its own screen, thereby preserving the cocoboot state long enough to load the Nitros9 kernel.
